# Generated by Django 3.0.8 on 2022-03-20 07:32

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(default='', max_length=100)),
                ('dayOfManufacture', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('insurance', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('description', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('keywordsSearch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
    ]
