# Generated by Django 4.0.3 on 2022-04-10 08:49

import Phone.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=Phone.models.create_phoneThumbnail_directory),
        ),
        migrations.CreateModel(
            name='PhoneImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=Phone.models.create_phoneImage_directory)),
                ('phone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Phone.phone')),
            ],
        ),
    ]
