# Generated by Django 3.0.8 on 2022-03-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='itemList',
        ),
        migrations.AddField(
            model_name='bills',
            name='itemList',
            field=models.ManyToManyField(blank=True, related_name='itemList', to='Phone.Phone'),
        ),
    ]
