# Generated by Django 3.0.8 on 2022-03-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20220319_1426'),
        ('Phone', '0002_auto_20220319_1415'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
