# Generated by Django 4.0.3 on 2022-04-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_phone_thumbnail_phoneimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='saleOff',
            field=models.FloatField(default=0),
        ),
    ]
