# Generated by Django 4.0.3 on 2022-05-15 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_alter_phone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='OS',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='RAM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='ROM',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='batteryCapacity',
            field=models.IntegerField(default=1000, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='chip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='mobileNetwork',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='numberOfSims',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='phoneCPU',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='screenResolution',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='screenSize',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='screenTechnique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phoneimage',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
