# Generated by Django 4.0.3 on 2022-05-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0003_phone_os_phone_ram_phone_rom_phone_batterycapacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='chip',
        ),
    ]
