# Generated by Django 4.0.3 on 2022-04-11 05:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0003_phone_saleoff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
