# Generated by Django 4.0.3 on 2022-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0004_remove_phone_chip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('apple', 'Apple'), ('asus', 'Asus'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('lg', 'LG'), ('vivo', 'Vivo'), ('xiaomi', 'Xiaomi')], default='Apple', max_length=100),
        ),
    ]
