# Generated by Django 4.0.3 on 2022-04-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0004_alter_phone_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(choices=[('apple', 'Apple'), ('asus', 'Asus'), ('htc', 'HTC'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('lg', 'LG'), ('vivo', 'Vivo'), ('xiaomi', 'Xiaomi')], default='Apple', max_length=100),
        ),
    ]
