# Generated by Django 4.0.3 on 2022-06-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0005_alter_phone_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['dayOfManufacture']},
        ),
    ]
