# Generated by Django 3.2.13 on 2022-04-25 06:43

import Blogs.models
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('releaseDate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('thumbnail', models.ImageField(default=None, upload_to=Blogs.models.create_phoneThumbnail_directory)),
                ('likes', models.IntegerField(default=0)),
                ('keywordsSearch', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
    ]
