# Generated by Django 4.0.3 on 2022-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tai nghe'), (2, 'Loa'), (3, 'Dây sạc'), (4, 'Smartwatch')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='brand',
            field=models.CharField(choices=[('apple', 'Apple'), ('asus', 'Asus'), ('htc', 'HTC'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('lg', 'LG'), ('vivo', 'Vivo'), ('xiaomi', 'Xiaomi')], default='apple', max_length=100),
        ),
    ]
