# Generated by Django 4.0.3 on 2022-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessory', '0002_alter_accessory_brand_alter_accessory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tai nghe'), (2, 'Loa'), (3, 'Dây sạc'), (4, 'Smartwatch')], default=1),
        ),
    ]
