# Generated by Django 4.0.3 on 2022-05-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accessory', '0003_alter_accessory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='brand',
            field=models.CharField(choices=[('apple', 'Apple'), ('asus', 'Asus'), ('samsung', 'Samsung'), ('huawei', 'Huawei'), ('lg', 'LG'), ('vivo', 'Vivo'), ('xiaomi', 'Xiaomi'), ('sony', 'Sony'), ('jbl', 'JBL')], default='apple', max_length=100),
        ),
    ]
