# Generated by Django 4.0.3 on 2022-05-16 13:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accessory', '0003_alter_accessory_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Phone', '0004_remove_phone_chip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_ht', models.FloatField(blank=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accessory.accessory')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cart.cart')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Phone.phone')),
            ],
        ),
    ]
