# Generated by Django 4.0.3 on 2022-05-16 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0004_remove_phone_chip'),
        ('Accessory', '0003_alter_accessory_category'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accessory.accessory'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Phone.phone'),
        ),
    ]
