# Generated by Django 4.0.3 on 2022-05-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_alter_cartitem_accessory_alter_cartitem_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price_ht',
        ),
    ]
