# Generated by Django 3.0.8 on 2022-03-20 07:32

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Phone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('displayName', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='', max_length=11, null=True)),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ')], default='M', max_length=1, null=True)),
                ('dateOfBirth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('wishList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('purchasedList', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('shoppingCart', models.ManyToManyField(blank=True, related_name='itemList', to='Phone.Phone')),
            ],
        ),
    ]
