# Generated by Django 3.0.8 on 2022-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0002_auto_20220319_1415'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='shoppingCart',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='shoppingCart',
            field=models.ManyToManyField(blank=True, related_name='billList', to='Phone.Bills'),
        ),
    ]
