# Generated by Django 3.0.8 on 2022-03-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Phone', '0003_delete_bills'),
        ('User', '0002_auto_20220319_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='shoppingCart',
            field=models.ManyToManyField(blank=True, related_name='itemList', to='Phone.Phone'),
        ),
    ]
