# Generated by Django 4.0.3 on 2022-05-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_order_paidtime_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
