# Generated by Django 4.0.3 on 2022-05-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
